name: Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-src

      - name: Install bpf-linker
        run: cargo +nightly install bpf-linker

      - uses: Swatinem/rust-cache@v1

      - name: Install Dependencies
        run: cargo install mdbook

      - name: Run tests
        run: mdbook build && mdbook test

      - name: Check Examples
        run: |
          for example in "aya-gen" "myapp-01" "myapp-02" "myapp-03"; do
            pushd "examples/${example}"
            echo "Example: ${example}."
            cargo xtask build-ebpf
            cargo build
            popd
          done

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: github.ref == 'refs/heads/main'
        with:
          branch: gh-pages
          folder: book
